# flutter_stripe ships the React Native Stripe SDK's Android sources, which
# reference Stripe's optional push-provisioning module (adding a card to Google
# Pay). We do not use that feature and the module is not on the classpath, so
# R8 stops at the dangling references and fails the release build.
#
# Silencing them is correct rather than a workaround: the code path is
# unreachable in this app, and the alternative is pulling in a Stripe module we
# have no use for. Generated by AGP into
# build/app/outputs/mapping/*/missing_rules.txt.
-dontwarn com.stripe.android.pushProvisioning.**
